# Generated by Django 4.0.1 on 2022-01-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
