# Generated by Django 4.0.1 on 2022-01-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0002_track_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.DateField(null=True),
        ),
    ]
