# Generated by Django 4.0.1 on 2022-01-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0005_review_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='track_id',
        ),
        migrations.AddField(
            model_name='review',
            name='item_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
