# Generated by Django 4.0.2 on 2022-02-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0006_remove_review_album_id_remove_review_track_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
