# Generated by Django 4.0.2 on 2022-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0008_artist_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='artist/bg_images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='artist/images/'),
        ),
    ]
