# Generated by Django 4.0.2 on 2022-02-21 17:45

from django.db import migrations, models
import django.utils.timezone
import reviewApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0009_alter_artist_background_image_alter_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created_at',
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to=reviewApp.models.RenameImageToSlug(
                'artist/bg_images/')),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=reviewApp.models.RenameImageToSlug(
                'artist/images/')),
        ),
    ]
