# Generated by Django 4.0.2 on 2022-02-21 18:14

from django.db import migrations, models
import reviewApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0011_alter_artist_background_image_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to=reviewApp.models.PathAndRename('artist/bg_images/')),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=reviewApp.models.PathAndRename('artist/images/')),
        ),
    ]
