# Generated by Django 4.0.2 on 2022-02-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0013_album_art_cover_alter_album_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='release_year',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='release_type',
            field=models.CharField(choices=[('LP', 'LP'), ('EP', 'EP'), ('S', 'Single'), ('Live', 'Live')], default='LP', max_length=10),
        ),
    ]
