# Generated by Django 4.0.2 on 2022-02-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0014_rename_release_year_album_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewed_item_type',
        ),
        migrations.AddField(
            model_name='review',
            name='album_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='reviewApp.album'),
            preserve_default=False,
        ),
    ]
