# Generated by Django 4.0.2 on 2022-02-22 18:13

from django.db import migrations, models
import reviewApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0016_artist_slug_review_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=reviewApp.models.RenameImageToSlug([('A', 'Artist Image'), ('ABG', 'Artist Background Image'), ('AC', 'Album Art Cover')]))),
                ('image_type', models.CharField(choices=[('A', 'Artist Image'), ('ABG', 'Artist Background Image'), ('AC', 'Album Art Cover')], default='AC', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='art_cover',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
    ]
