# Generated by Django 4.0.2 on 2022-02-22 21:26

from django.db import migrations, models
import reviewApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0017_image_remove_album_art_cover_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='album',
            name='art_cover',
            field=models.FileField(blank=True, null=True, upload_to=reviewApp.models.RenameImageToSlug('album/art_covers/')),
        ),
        migrations.AddField(
            model_name='artist',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to=reviewApp.models.RenameImageToSlug('artist/bg_images/')),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=reviewApp.models.RenameImageToSlug('artist/images/')),
        ),
    ]
