# Generated by Django 4.0.2 on 2022-02-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0018_delete_image_album_art_cover_artist_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
