# Generated by Django 4.0.2 on 2022-02-22 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0019_alter_artist_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_genres', to='reviewApp.album')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_genres', to='reviewApp.genres')),
            ],
        ),
    ]
