# Generated by Django 4.0.2 on 2022-02-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0020_genres_albumgenres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumGenres',
            new_name='AlbumGenre',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
