# Generated by Django 4.0.2 on 2022-02-22 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0021_rename_albumgenres_albumgenre_rename_genres_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('spotify', 'Spotify'), ('tidal', 'Tidal'), (
                    'amazon_music', 'Amazon Music'), ('apple_music', 'Apple Music')], max_length=15)),
                ('url', models.CharField(max_length=255)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='album_links', to='reviewApp.album')),
            ],
        ),
    ]
