# Generated by Django 4.0.2 on 2022-02-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0024_alter_albumoftheyear_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_type',
            field=models.CharField(choices=[('LP', 'LP'), ('EP', 'EP'), ('Single', 'Single'), ('Live', 'Live')], default='LP', max_length=10),
        ),
    ]
