# Generated by Django 4.0.2 on 2022-02-25 13:56

from django.db import migrations, models
import reviewApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0025_alter_album_release_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=reviewApp.models.RenameImageToSlug('users/profile_pics/')),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
