# Generated by Django 4.0.2 on 2022-02-25 14:05

from django.db import migrations
import django_resized.forms
import reviewApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0026_reviewer_profile_pic_reviewer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='art_cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, size=[750, 750], upload_to=reviewApp.models.RenameImageToSlug('album/art_covers/')),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, size=[500, 500], upload_to=reviewApp.models.RenameImageToSlug('artist/images/')),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, size=[500, 500], upload_to=reviewApp.models.RenameImageToSlug('users/profile_pics/')),
        ),
    ]
