# Generated by Django 4.0.2 on 2022-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0027_alter_album_art_cover_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
