# Generated by Django 4.0.2 on 2022-02-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0028_alter_review_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteReviewerArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewApp.artist')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewApp.reviewer')),
            ],
        ),
    ]
