# Generated by Django 4.0.2 on 2022-02-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0029_favoritereviewerartist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritereviewerartist',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_artist', to='reviewApp.artist'),
        ),
        migrations.AlterField(
            model_name='favoritereviewerartist',
            name='reviewer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_artist', to='reviewApp.reviewer'),
        ),
    ]
