# Generated by Django 4.0.2 on 2022-02-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0030_alter_favoritereviewerartist_artist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritereviewerartist',
            name='reviewer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_artist', to='reviewApp.reviewer'),
        ),
    ]
