# Generated by Django 4.0.2 on 2022-02-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0031_alter_favoritereviewerartist_reviewer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
