# Generated by Django 4.0.2 on 2022-02-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0032_reviewer_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('spotify', 'Spotify'), ('twitter', 'Twitter'), ('lastFm', 'Last.FM')], max_length=15)),
                ('url', models.CharField(max_length=255)),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewer_links', to='reviewApp.reviewer')),
            ],
        ),
    ]
