# Generated by Django 4.0.2 on 2022-02-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0033_reviewerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
