# Generated by Django 4.0.2 on 2022-03-06 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0034_alter_album_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewApp.reviewer'),
        ),
        migrations.AlterField(
            model_name='albumgenre',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_genres', to='reviewApp.album'),
        ),
        migrations.AlterField(
            model_name='albumlink',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_links', to='reviewApp.album'),
        ),
        migrations.AlterField(
            model_name='albumoftheyear',
            name='album_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aoty', to='reviewApp.album'),
        ),
        migrations.AlterField(
            model_name='review',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviewApp.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='reviewApp.album'),
        ),
    ]
