# Generated by Django 4.0.2 on 2022-03-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0035_album_create_by_alter_albumgenre_album_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewApp.reviewer'),
        ),
    ]
