# Generated by Django 4.0.2 on 2022-03-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0036_artist_create_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
