# Generated by Django 4.0.2 on 2022-03-13 20:57

from django.db import migrations
import django_resized.forms
import reviewApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0040_alter_album_art_cover_alter_artist_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='art_cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, max_length=255, null=True, quality=90, size=[750, 750], upload_to=reviewApp.models.RenameImageToSlug('album/art_covers/')),
        ),
        migrations.AlterField(
            model_name='artist',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=255, null=True, quality=90, size=[1920, 1080], upload_to=reviewApp.models.RenameImageToSlug('artist/bg_images/')),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, max_length=255, null=True, quality=90, size=[500, 500], upload_to=reviewApp.models.RenameImageToSlug('artist/images/')),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=255, null=True, quality=90, size=[500, 500], upload_to='users/profile_pics/'),
        ),
    ]
