# Generated by Django 4.0.2 on 2022-03-13 21:32

from django.db import migrations, models
import django_resized.forms
import reviewApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0041_alter_album_art_cover_alter_artist_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='art_cover_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='art_cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=255, null=True, quality=90, size=[750, 750], upload_to=reviewApp.models.RenameImageToSlug('album/art_covers/')),
        ),
    ]
