# Generated by Django 4.0.2 on 2022-03-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0043_artist_background_image_url_artist_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
