# Generated by Django 4.0.3 on 2022-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0044_reviewer_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='art_cover_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='albumlink',
            name='url',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='artist',
            name='background_image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='reviewerlink',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
