# Generated by Django 4.0.3 on 2022-03-14 21:11

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0045_alter_album_art_cover_url_alter_albumlink_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
