# Generated by Django 4.0.3 on 2022-03-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0046_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumlink',
            name='service_name',
            field=models.CharField(choices=[('spotify', 'Spotify'), ('tidal', 'Tidal'), ('amazonMusic', 'Amazon Music'), ('appleMusic', 'Apple Music')], max_length=15),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewerlink',
            name='service_name',
            field=models.CharField(choices=[('spotify', 'Spotify'), ('twitter', 'Twitter'), ('last_fm', 'Last.FM')], max_length=15),
        ),
    ]
