# Generated by Django 4.0.3 on 2022-05-31 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0047_alter_albumlink_service_name_alter_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumlink',
            name='service_name',
            field=models.CharField(choices=[('spotify', 'Spotify'), ('tidal', 'Tidal'), ('amazon_music', 'Amazon Music'), ('apple_music', 'Apple Music')], max_length=15),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewApp.review')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewApp.reviewer')),
            ],
        ),
    ]
