# Generated by Django 4.0.3 on 2022-05-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0048_alter_albumlink_service_name_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='reviewer_id',
        ),
    ]
